services:
  postgres_db:
    image: postgres:17
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - api_network
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    environment:
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - SECRECT_KEY=${SECRECT_KEY}
      - ALGORITHM=${ALGORITHM}
    ports:
      - ${PORT}:${PORT}
    container_name : api-aiqfome
    networks:
      - api_network

networks:
  api_network:
    driver: bridge